#ifndef PARSER_H
#define PARSER_H

#include "syntaxtree.h"

enum parsing_status {
    PARSING_OK,
    PARSING_ERROR_SOURCE_NULL,
    PARSING_ERROR_EXTRA_CHARACTERS,
    PARSING_ERROR_NO_EXPRESSION,
    PARSING_ERROR_NO_OPERAND_OF_BINARY_OP,
    PARSING_ERROR_NO_OPERAND_OF_UNARY_OP,
    PARSING_ERROR_NO_RIGHT_PARENTHESIS,
    PARSING_ERROR_NO_VARIABLE_NAME,
    PARSING_ERROR_NO_EQUAL_OP,
    PARSING_ERROR_NO_ASSIGNMENT_VALUE
};

struct syntax_node *parse( const char *source );
enum parsing_status parsing_status();

#endif // PARSER_H
